GET http://localhost:8080/hello?name=jinu
###
POST http://localhost
Content-Type: application/json

###
GET http://localhost:8080/hello?name=Spring

###
POST http://localhost:8080/hello?name=Spring


